# Generated by Django 5.0.2 on 2024-02-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotDeLettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('text_original', models.TextField()),
                ('text_traduction', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('lot_de_lettre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettres', to='core.lotdelettre')),
            ],
        ),
    ]
