# Generated by Django 5.0.2 on 2024-02-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettre',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
