# Generated by Django 5.0.2 on 2024-02-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lettre_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettre',
            name='status',
            field=models.CharField(choices=[('Lire', 'Lire'), ('Lu', 'Lu'), ('Traduire', 'Traduire'), ('Faite', 'Faite')], default='Lire', max_length=10),
        ),
        migrations.AlterField(
            model_name='lettre',
            name='text_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lettre',
            name='text_traduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotdelettre',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
